# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
lleg_ankle_p_position:
  type: effort_controllers/JointPositionController
  joint: lleg_ankle_p
  pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_046_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_046_joint
      pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
lleg_crotch_p_position:
  type: effort_controllers/JointPositionController
  joint: lleg_crotch_p
  pid: {p: 40000000.000000, i: 4000000.000000, d: 2000000.000000}
  mimic_joints:
    rx78_Null_034_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_034_joint
      pid: {p: 50000.000000, i: 500.000000, d: 5000.000000}
    rx78_Null_033_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_033_joint
      pid: {p: 50000.000000, i: 500.000000, d: 5000.000000}
lleg_crotch_y_position:
  type: effort_controllers/JointPositionController
  joint: lleg_crotch_y
  pid: {p: 20000000.000000, i: 1000000.000000, d: 1000000.000000}
lleg_knee_p_position:
  type: effort_controllers/JointPositionController
  joint: lleg_knee_p
  pid: {p: 10000000.000000, i: 100000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_038_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_038_joint
      pid: {p: 10000000.000000, i: 100000.000000, d: 1000000.000000}
rarm_shoulder_p_position:
  type: effort_controllers/JointPositionController
  joint: rarm_shoulder_p
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
lleg_ankle_r_position:
  type: effort_controllers/JointPositionController
  joint: lleg_ankle_r
  pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_040_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_040_joint
      pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
rarm_elbow_p_position:
  type: effort_controllers/JointPositionController
  joint: rarm_elbow_p
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
  mimic_joints:
    rx78_Null_053_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_053_joint
      pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
rarm_shoulder_r_position:
  type: effort_controllers/JointPositionController
  joint: rarm_shoulder_r
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
rarm_shoulder_y_position:
  type: effort_controllers/JointPositionController
  joint: rarm_shoulder_y
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
rarm_gripper_position:
  type: effort_controllers/JointPositionController
  joint: rarm_gripper
  pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
  mimic_joints:
    rx78_Null_058_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_058_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_057_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_057_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_080_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_080_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_078_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_078_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_079_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_079_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_023_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_023_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_022_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_022_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_021_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_021_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_027_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_027_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_026_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_026_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_025_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_025_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_024_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_024_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_029_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_029_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_028_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_028_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
rarm_wrist_y_position:
  type: effort_controllers/JointPositionController
  joint: rarm_wrist_y
  pid: {p: 100000.000000, i: 50.000000, d: 20000.000000}
rarm_wrist_r_position:
  type: effort_controllers/JointPositionController
  joint: rarm_wrist_r
  pid: {p: 100000.000000, i: 50.000000, d: 20000.000000}
larm_wrist_y_position:
  type: effort_controllers/JointPositionController
  joint: larm_wrist_y
  pid: {p: 100000.000000, i: 50.000000, d: 20000.000000}
larm_gripper_position:
  type: effort_controllers/JointPositionController
  joint: larm_gripper
  pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
  mimic_joints:
    rx78_Null_059_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_059_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_064_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_064_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_063_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_063_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_061_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_061_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_060_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_060_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_068_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_068_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_070_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_070_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_071_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_071_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_072_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_072_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_073_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_073_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_074_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_074_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_075_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_075_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_076_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_076_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
    rx78_Null_077_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_077_joint
      pid: {p: 5000.000000, i: 100.000000, d: 1000.000000}
larm_wrist_r_position:
  type: effort_controllers/JointPositionController
  joint: larm_wrist_r
  pid: {p: 100000.000000, i: 50.000000, d: 20000.000000}
larm_shoulder_p_position:
  type: effort_controllers/JointPositionController
  joint: larm_shoulder_p
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
larm_shoulder_r_position:
  type: effort_controllers/JointPositionController
  joint: larm_shoulder_r
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
larm_elbow_p_position:
  type: effort_controllers/JointPositionController
  joint: larm_elbow_p
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
  mimic_joints:
    rx78_Null_066_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_066_joint
      pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
larm_shoulder_y_position:
  type: effort_controllers/JointPositionController
  joint: larm_shoulder_y
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
lleg_crotch_r_position:
  type: effort_controllers/JointPositionController
  joint: lleg_crotch_r
  pid: {p: 20000000.000000, i: 1000000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_047_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_047_joint
      pid: {p: 50000.000000, i: 500.000000, d: 5000.000000}
rleg_ankle_p_position:
  type: effort_controllers/JointPositionController
  joint: rleg_ankle_p
  pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_030_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_030_joint
      pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
rleg_crotch_p_position:
  type: effort_controllers/JointPositionController
  joint: rleg_crotch_p
  pid: {p: 40000000.000000, i: 4000000.000000, d: 2000000.000000}
  mimic_joints:
    rx78_Null_031_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_031_joint
      pid: {p: 50000.000000, i: 500.000000, d: 5000.000000}
    rx78_Null_084_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_084_joint
      pid: {p: 50000.000000, i: 500.000000, d: 5000.000000}
rleg_knee_p_position:
  type: effort_controllers/JointPositionController
  joint: rleg_knee_p
  pid: {p: 10000000.000000, i: 100000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_088_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_088_joint
      pid: {p: 10000000.000000, i: 100000.000000, d: 1000000.000000}
rleg_crotch_y_position:
  type: effort_controllers/JointPositionController
  joint: rleg_crotch_y
  pid: {p: 20000000.000000, i: 1000000.000000, d: 1000000.000000}
torso_waist_p_position:
  type: effort_controllers/JointPositionController
  joint: torso_waist_p
  pid: {p: 20000000.000000, i: 10000.000000, d: 2000000.000000}
  mimic_joints:
    rx78_Null_016_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_016_joint
      pid: {p: 20000000.000000, i: 10000.000000, d: 2000000.000000}
head_neck_p_position:
  type: effort_controllers/JointPositionController
  joint: head_neck_p
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
head_neck_y_position:
  type: effort_controllers/JointPositionController
  joint: head_neck_y
  pid: {p: 1000000.000000, i: 500.000000, d: 200000.000000}
torso_waist_y_position:
  type: effort_controllers/JointPositionController
  joint: torso_waist_y
  pid: {p: 20000000.000000, i: 10000.000000, d: 2000000.000000}
rleg_ankle_r_position:
  type: effort_controllers/JointPositionController
  joint: rleg_ankle_r
  pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_090_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_090_joint
      pid: {p: 10000000.000000, i: 5000.000000, d: 1000000.000000}
rleg_crotch_r_position:
  type: effort_controllers/JointPositionController
  joint: rleg_crotch_r
  pid: {p: 20000000.000000, i: 1000000.000000, d: 1000000.000000}
  mimic_joints:
    rx78_Null_032_joint_position:
      type: effort_controllers/JointPositionController
      joint: rx78_Null_032_joint
      pid: {p: 50000.000000, i: 500.000000, d: 5000.000000}
